[phases.setup]
nixPkgs = ["ffmpeg", "python3", "python3-pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python setup_railway.py"]

[start]
cmd = "python bot.py" 